[build]
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-js-obfuscator"

  [plugins.inputs]
  compact = true
  numbersToExpressions = true
  simplify = true
  shuffleStringArray = true
  splitStrings = true
